#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys


def main():

    parser = argparse.ArgumentParser(description="Publish Docker images")
    parser.add_argument("--image", dest="image", help="The image to be exported")
    parser.add_argument("--tag", dest="tag", default="dockerhub", help="Used repository",)
    args = parser.parse_args()
    image = args.image
    tag = args.tag

    sys.stdout.flush()

    cmd = ["docker", "login"]
    login = subprocess.check_output(["gopass", "gs/ci/dockerhub/username"]).decode()
    password = subprocess.check_output(["gopass", "gs/ci/dockerhub/password"])
    prefix = ""
    cmd += ["--username=" + login, "--password-stdin"]
    process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    output, output_err = process.communicate(input=password)
    if process.returncode != 0:
        if output:
            print(output.decode())
        if output_err:
            print(output_err.decode())
        sys.exit(1)

    full_image = f"camptocamp/{image}:{tag}"
    subprocess.check_call(["docker", "push", full_image])

if __name__ == "__main__":
    main()
