name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on:
      ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Docker image
        run: docker build -t lyrx2sld .
      - name: Run
        run: docker run -d -p 80:80 lyrx2sld

  publish:
    runs-on:
      ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
