name: CI

on: 
  push
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

jobs:
  build:
    runs-on:
      ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t lyrx2sld .