name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on:
      ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Docker image
        run: docker build -t lyrx2sld .

  publish:
    runs-on:
      ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Docker image
        run: docker build -t vuilleumierc/lyrx2sld:latest .
      - name: Publish image to Docker Hub
        run: docker push vuilleumierc/lyrx2sld:latest