name: 'Synchronize bridge-style'

on: [push, workflow_dispatch]

jobs:
  sync:
    runs-on:
      ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update git submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Build Docker image
        run: docker build -t lyrx2sld .
      - name: Run
        run: docker run -d -p 80:80 lyrx2sld
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python tests
        run: pytest tests/tests.py -v
      - name: Commit update
        run: |
          git config --global user.name 'c2c-bot-gis-ci'
          git config --global user.email 'c2c-bot-gis-ci@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
